-- Borrowing records. loan code is generated from a dedicated sequence.
CREATE SEQUENCE loan_code_seq START 1000 INCREMENT 1;

CREATE TABLE loans (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20) NOT NULL UNIQUE,
    member_id    BIGINT      NOT NULL REFERENCES members (id),
    book_copy_id BIGINT      NOT NULL REFERENCES book_copies (id),
    borrow_date  DATE        NOT NULL,
    due_date     DATE        NOT NULL,
    return_date  DATE,
    status       VARCHAR(20) NOT NULL,
    renew_count  INT         NOT NULL DEFAULT 0,
    created_by   BIGINT REFERENCES users (id),
    returned_by  BIGINT REFERENCES users (id),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_loans_member_id ON loans (member_id);
CREATE INDEX idx_loans_book_copy_id ON loans (book_copy_id);
CREATE INDEX idx_loans_status ON loans (status);
CREATE INDEX idx_loans_due_date ON loans (due_date);
