-- Monetary penalties. Amount in VND (whole numbers) as NUMERIC.
CREATE TABLE fines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT         NOT NULL REFERENCES members (id),
    loan_id    BIGINT REFERENCES loans (id),
    type       VARCHAR(20)    NOT NULL,
    amount     NUMERIC(15, 2) NOT NULL,
    status     VARCHAR(20)    NOT NULL,
    reason     VARCHAR(500),
    paid_at    TIMESTAMPTZ,
    settled_by BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ    NOT NULL,
    updated_at TIMESTAMPTZ    NOT NULL
);

CREATE INDEX idx_fines_member_id ON fines (member_id);
CREATE INDEX idx_fines_loan_id ON fines (loan_id);
CREATE INDEX idx_fines_status ON fines (status);
CREATE INDEX idx_fines_type ON fines (type);
