-- Title level holds. created_at is the reservation date and the FIFO queue key.
CREATE TABLE reservations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT      NOT NULL REFERENCES members (id),
    book_id      BIGINT      NOT NULL REFERENCES books (id),
    held_copy_id BIGINT REFERENCES book_copies (id),
    status       VARCHAR(20) NOT NULL,
    ready_at     TIMESTAMPTZ,
    pickup_expiry DATE,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_reservations_book_id ON reservations (book_id);
CREATE INDEX idx_reservations_member_id ON reservations (member_id);
CREATE INDEX idx_reservations_status ON reservations (status);
CREATE INDEX idx_reservations_held_copy_id ON reservations (held_copy_id);
