-- Book authors.
CREATE TABLE authors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(255) NOT NULL,
    biography  VARCHAR(2000),
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_authors_full_name ON authors (full_name);
CREATE INDEX idx_authors_status ON authors (status);
