-- Bibliographic book records. total_copies/available_copies are denormalized counters kept
-- consistent with the book_copies rows inside the same transaction as any copy change.
CREATE TABLE books (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(20)  NOT NULL UNIQUE,
    title            VARCHAR(500) NOT NULL,
    subtitle         VARCHAR(500),
    description      VARCHAR(4000),
    publisher_id     BIGINT REFERENCES publishers (id),
    category_id      BIGINT REFERENCES categories (id),
    publication_year INT,
    language         VARCHAR(50),
    page_count       INT,
    cover_image_url  VARCHAR(1024),
    total_copies     INT          NOT NULL DEFAULT 0,
    available_copies INT          NOT NULL DEFAULT 0,
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_books_title ON books (title);
CREATE INDEX idx_books_category_id ON books (category_id);
CREATE INDEX idx_books_publisher_id ON books (publisher_id);
CREATE INDEX idx_books_status ON books (status);
