-- Physical copies. version drives optimistic locking to prevent double checkout of one copy.
CREATE TABLE book_copies (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id        BIGINT       NOT NULL REFERENCES books (id),
    barcode        VARCHAR(64)  NOT NULL UNIQUE,
    shelf_location VARCHAR(100),
    status         VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    acquired_date  DATE,
    condition_note VARCHAR(1000),
    version        BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_book_copies_book_id ON book_copies (book_id);
CREATE INDEX idx_book_copies_status ON book_copies (status);
