-- Library readers. member_code is generated from a dedicated sequence.
CREATE SEQUENCE member_code_seq START 1000 INCREMENT 1;

CREATE TABLE members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code     VARCHAR(20)  NOT NULL UNIQUE,
    full_name       VARCHAR(255) NOT NULL,
    email           VARCHAR(320) NOT NULL UNIQUE,
    phone           VARCHAR(30),
    address         VARCHAR(500),
    membership_type VARCHAR(20)  NOT NULL,
    join_date       DATE         NOT NULL,
    expiry_date     DATE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_members_full_name ON members (full_name);
CREATE INDEX idx_members_phone ON members (phone);
CREATE INDEX idx_members_status ON members (status);
CREATE INDEX idx_members_membership_type ON members (membership_type);
